# config.py

# RPC URLs for different blockchains
RPC_URLS = {
    "ethereum": "https://eth.llamarpc.com/",
    "bsc": "https://binance.llamarpc.com/",
}

# Contract addresses on Ethereum and BSC
CONTRACT_ADDRESSES = {
    "ethereum": {
        "usdc": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "weth": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    },
    "bsc": {
        "usdc": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
        "wbnb": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
    },
}

# Uniswap V2 Factory ABI snippet. This is not the complete ABI but gives an example of the structure.
# For the full ABI, you would need to visit the Uniswap GitHub repository or Etherscan.
UNI_ROUTER_ABI = [{'inputs': [{'internalType': 'address', 'name': '_factory', 'type': 'address'},
                              {'internalType': 'address', 'name': '_WETH', 'type': 'address'}],
                       'stateMutability': 'nonpayable', 'type': 'constructor'}, {'inputs': [], 'name': 'WETH',
                                                                                 'outputs': [{'internalType': 'address',
                                                                                              'name': '',
                                                                                              'type': 'address'}],
                                                                                 'stateMutability': 'view',
                                                                                 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'tokenA', 'type': 'address'},
                                     {'internalType': 'address', 'name': 'tokenB', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'amountADesired', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountBDesired', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountAMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountBMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'addLiquidity',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'token', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'amountTokenDesired', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'addLiquidityETH',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountToken', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'}],
                          'stateMutability': 'payable', 'type': 'function'}, {'inputs': [], 'name': 'factory',
                                                                              'outputs': [{'internalType': 'address',
                                                                                           'name': '',
                                                                                           'type': 'address'}],
                                                                              'stateMutability': 'view',
                                                                              'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'reserveIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'reserveOut', 'type': 'uint256'}],
                          'name': 'getAmountIn',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'}],
                          'stateMutability': 'pure', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'reserveIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'reserveOut', 'type': 'uint256'}],
                          'name': 'getAmountOut',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256'}],
                          'stateMutability': 'pure', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'}],
                          'name': 'getAmountsIn',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'view', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'}],
                          'name': 'getAmountsOut',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'view', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'reserveA', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'reserveB', 'type': 'uint256'}],
                          'name': 'quote',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256'}],
                          'stateMutability': 'pure', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'tokenA', 'type': 'address'},
                                     {'internalType': 'address', 'name': 'tokenB', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountAMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountBMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'removeLiquidity',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'token', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'removeLiquidityETH',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountToken', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'token', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'removeLiquidityETHSupportingFeeOnTransferTokens',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'token', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'},
                                     {'internalType': 'bool', 'name': 'approveMax', 'type': 'bool'},
                                     {'internalType': 'uint8', 'name': 'v', 'type': 'uint8'},
                                     {'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32'},
                                     {'internalType': 'bytes32', 'name': 's', 'type': 'bytes32'}],
                          'name': 'removeLiquidityETHWithPermit',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountToken', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'token', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountTokenMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountETHMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'},
                                     {'internalType': 'bool', 'name': 'approveMax', 'type': 'bool'},
                                     {'internalType': 'uint8', 'name': 'v', 'type': 'uint8'},
                                     {'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32'},
                                     {'internalType': 'bytes32', 'name': 's', 'type': 'bytes32'}],
                          'name': 'removeLiquidityETHWithPermitSupportingFeeOnTransferTokens',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountETH', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'address', 'name': 'tokenA', 'type': 'address'},
                                     {'internalType': 'address', 'name': 'tokenB', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountAMin', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountBMin', 'type': 'uint256'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'},
                                     {'internalType': 'bool', 'name': 'approveMax', 'type': 'bool'},
                                     {'internalType': 'uint8', 'name': 'v', 'type': 'uint8'},
                                     {'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32'},
                                     {'internalType': 'bytes32', 'name': 's', 'type': 'bytes32'}],
                          'name': 'removeLiquidityWithPermit',
                          'outputs': [{'internalType': 'uint256', 'name': 'amountA', 'type': 'uint256'},
                                      {'internalType': 'uint256', 'name': 'amountB', 'type': 'uint256'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapETHForExactTokens',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'payable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapExactETHForTokens',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'payable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapExactETHForTokensSupportingFeeOnTransferTokens', 'outputs': [],
                          'stateMutability': 'payable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapExactTokensForETH',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapExactTokensForETHSupportingFeeOnTransferTokens', 'outputs': [],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapExactTokensForTokens',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountIn', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountOutMin', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapExactTokensForTokensSupportingFeeOnTransferTokens', 'outputs': [],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountInMax', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapTokensForExactETH',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'nonpayable', 'type': 'function'}, {
                          'inputs': [{'internalType': 'uint256', 'name': 'amountOut', 'type': 'uint256'},
                                     {'internalType': 'uint256', 'name': 'amountInMax', 'type': 'uint256'},
                                     {'internalType': 'address[]', 'name': 'path', 'type': 'address[]'},
                                     {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                     {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}],
                          'name': 'swapTokensForExactTokens',
                          'outputs': [{'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]'}],
                          'stateMutability': 'nonpayable', 'type': 'function'},
                  {'stateMutability': 'payable', 'type': 'receive'}]

UNI_FACTORY_ABI = [
            {'inputs': [{'internalType': 'address', 'name': '_feeToSetter', 'type': 'address'}], 'payable': False,
             'stateMutability': 'nonpayable', 'type': 'constructor'}, {'anonymous': False, 'inputs': [
                {'indexed': True, 'internalType': 'address', 'name': 'token0', 'type': 'address'},
                {'indexed': True, 'internalType': 'address', 'name': 'token1', 'type': 'address'},
                {'indexed': False, 'internalType': 'address', 'name': 'pair', 'type': 'address'},
                {'indexed': False, 'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'name': 'PairCreated',
                                                                       'type': 'event'},
            {'constant': True, 'inputs': [], 'name': 'INIT_CODE_PAIR_HASH',
             'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}], 'payable': False,
             'stateMutability': 'view', 'type': 'function'},
            {'constant': True, 'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
             'name': 'allPairs', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
             'payable': False, 'stateMutability': 'view', 'type': 'function'},
            {'constant': True, 'inputs': [], 'name': 'allPairsLength',
             'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False,
             'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [
                {'internalType': 'address', 'name': 'tokenA', 'type': 'address'},
                {'internalType': 'address', 'name': 'tokenB', 'type': 'address'}], 'name': 'createPair', 'outputs': [
                {'internalType': 'address', 'name': 'pair', 'type': 'address'}], 'payable': False,
                                                              'stateMutability': 'nonpayable', 'type': 'function'},
            {'constant': True, 'inputs': [], 'name': 'feeTo',
             'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'payable': False,
             'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'feeToSetter',
                                                              'outputs': [{'internalType': 'address', 'name': '',
                                                                           'type': 'address'}], 'payable': False,
                                                              'stateMutability': 'view', 'type': 'function'},
            {'constant': True, 'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'},
                                          {'internalType': 'address', 'name': '', 'type': 'address'}],
             'name': 'getPair', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
             'payable': False, 'stateMutability': 'view', 'type': 'function'},
            {'constant': False, 'inputs': [{'internalType': 'address', 'name': '_feeTo', 'type': 'address'}],
             'name': 'setFeeTo', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
            {'constant': False, 'inputs': [{'internalType': 'address', 'name': '_feeToSetter', 'type': 'address'}],
             'name': 'setFeeToSetter', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable',
             'type': 'function'}]

UNI_PAIR_CONTRACT_ABI = [{'inputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'}, {'indexed': True, 'internalType': 'address', 'name': 'spender', 'type': 'address'}, {'indexed': False, 'internalType': 'uint256', 'name': 'value', 'type': 'uint256'}], 'name': 'Approval', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'sender', 'type': 'address'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount0', 'type': 'uint256'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount1', 'type': 'uint256'}, {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'}], 'name': 'Burn', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'sender', 'type': 'address'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount0', 'type': 'uint256'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount1', 'type': 'uint256'}], 'name': 'Mint', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'sender', 'type': 'address'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount0In', 'type': 'uint256'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount1In', 'type': 'uint256'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount0Out', 'type': 'uint256'}, {'indexed': False, 'internalType': 'uint256', 'name': 'amount1Out', 'type': 'uint256'}, {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'}], 'name': 'Swap', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': False, 'internalType': 'uint112', 'name': 'reserve0', 'type': 'uint112'}, {'indexed': False, 'internalType': 'uint112', 'name': 'reserve1', 'type': 'uint112'}], 'name': 'Sync', 'type': 'event'}, {'anonymous': False, 'inputs': [{'indexed': True, 'internalType': 'address', 'name': 'from', 'type': 'address'}, {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'}, {'indexed': False, 'internalType': 'uint256', 'name': 'value', 'type': 'uint256'}], 'name': 'Transfer', 'type': 'event'}, {'constant': True, 'inputs': [], 'name': 'DOMAIN_SEPARATOR', 'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'MINIMUM_LIQUIDITY', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'PERMIT_TYPEHASH', 'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}, {'internalType': 'address', 'name': '', 'type': 'address'}], 'name': 'allowance', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'spender', 'type': 'address'}, {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'}], 'name': 'approve', 'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'name': 'balanceOf', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}], 'name': 'burn', 'outputs': [{'internalType': 'uint256', 'name': 'amount0', 'type': 'uint256'}, {'internalType': 'uint256', 'name': 'amount1', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'decimals', 'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'factory', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'getReserves', 'outputs': [{'internalType': 'uint112', 'name': '_reserve0', 'type': 'uint112'}, {'internalType': 'uint112', 'name': '_reserve1', 'type': 'uint112'}, {'internalType': 'uint32', 'name': '_blockTimestampLast', 'type': 'uint32'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': '_token0', 'type': 'address'}, {'internalType': 'address', 'name': '_token1', 'type': 'address'}], 'name': 'initialize', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'kLast', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}], 'name': 'mint', 'outputs': [{'internalType': 'uint256', 'name': 'liquidity', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'name', 'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'name': 'nonces', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}, {'internalType': 'address', 'name': 'spender', 'type': 'address'}, {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'}, {'internalType': 'uint256', 'name': 'deadline', 'type': 'uint256'}, {'internalType': 'uint8', 'name': 'v', 'type': 'uint8'}, {'internalType': 'bytes32', 'name': 'r', 'type': 'bytes32'}, {'internalType': 'bytes32', 'name': 's', 'type': 'bytes32'}], 'name': 'permit', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'price0CumulativeLast', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'price1CumulativeLast', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}], 'name': 'skim', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'uint256', 'name': 'amount0Out', 'type': 'uint256'}, {'internalType': 'uint256', 'name': 'amount1Out', 'type': 'uint256'}, {'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'}], 'name': 'swap', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'symbol', 'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [], 'name': 'sync', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'token0', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'token1', 'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': True, 'inputs': [], 'name': 'totalSupply', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'}], 'name': 'transfer', 'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}, {'constant': False, 'inputs': [{'internalType': 'address', 'name': 'from', 'type': 'address'}, {'internalType': 'address', 'name': 'to', 'type': 'address'}, {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'}], 'name': 'transferFrom', 'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}]

UNI_CONTRACT_ABI = [{'inputs': [],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'constructor'},
                    {'anonymous': False,
  'inputs': [{'indexed': True,
              'internalType': 'address',
              'name': 'owner',
              'type': 'address'},
             {'indexed': True,
              'internalType': 'address',
              'name': 'spender',
              'type': 'address'},
             {'indexed': False,
              'internalType': 'uint256',
              'name': 'value',
              'type': 'uint256'}],
  'name': 'Approval',
  'type': 'event'},
                    {'anonymous': False,
  'inputs': [{'indexed': True,
              'internalType': 'address',
              'name': 'previousOwner',
              'type': 'address'},
             {'indexed': True,
              'internalType': 'address',
              'name': 'newOwner',
              'type': 'address'}],
  'name': 'OwnershipTransferred',
  'type': 'event'},
                    {'anonymous': False,
  'inputs': [{'indexed': True,
              'internalType': 'address',
              'name': 'from',
              'type': 'address'},
             {'indexed': True,
              'internalType': 'address',
              'name': 'to',
              'type': 'address'},
             {'indexed': False,
              'internalType': 'uint256',
              'name': 'value',
              'type': 'uint256'}],
  'name': 'Transfer',
  'type': 'event'},
                    {'constant': True,
  'inputs': [],
  'name': '_decimals',
  'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': '_name',
  'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': '_symbol',
  'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': True,
  'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'},
             {'internalType': 'address', 'name': 'spender', 'type': 'address'}],
  'name': 'allowance',
  'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {
                        "constant": False,
                        "inputs": [
                            {
                                "name": "_spender",
                                "type": "address"
                            },
                            {
                                "name": "_value",
                                "type": "uint256"
                            }
                        ],
                        "name": "approve",
                        "outputs": [
                            {
                                "name": "success",
                                "type": "bool"
                            }
                        ],
                        "payable": False,
                        "type": "function"
                    },
                    {'constant': True,
  'inputs': [{'internalType': 'address', 'name': 'account', 'type': 'address'}],
  'name': 'balanceOf',
  'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'burn',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': 'decimals',
  'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'address', 'name': 'spender', 'type': 'address'},
             {'internalType': 'uint256',
              'name': 'subtractedValue',
              'type': 'uint256'}],
  'name': 'decreaseAllowance',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': 'getOwner',
  'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'address', 'name': 'spender', 'type': 'address'},
             {'internalType': 'uint256',
              'name': 'addedValue',
              'type': 'uint256'}],
  'name': 'increaseAllowance',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'mint',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': 'name',
  'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': 'owner',
  'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': False,
  'inputs': [],
  'name': 'renounceOwnership',
  'outputs': [],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': 'symbol',
  'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': True,
  'inputs': [],
  'name': 'totalSupply',
  'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
  'payable': False,
  'stateMutability': 'view',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'address',
              'name': 'recipient',
              'type': 'address'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'transfer',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'address', 'name': 'sender', 'type': 'address'},
             {'internalType': 'address',
              'name': 'recipient',
              'type': 'address'},
             {'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'}],
  'name': 'transferFrom',
  'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'},
                    {'constant': False,
  'inputs': [{'internalType': 'address',
              'name': 'newOwner',
              'type': 'address'}],
  'name': 'transferOwnership',
  'outputs': [],
  'payable': False,
  'stateMutability': 'nonpayable',
  'type': 'function'}]